trigger:
- main
pr:
- main

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Stage artifacts'
    inputs:
      command: publish
      publishWebProjects: True
      arguments: '--configuration Release --runtime linux-x64 --self-contained --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: True

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'azureConnection'
      WebAppName: $(TestWebAppName)
      packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
