trigger:
- main
pr:
- main

stages:
- stage:
  jobs:
  - job:
    steps:
      - task: Docker@2
        displayName: Login to container registry
        inputs:
          containerRegistry: $(containerRegistry)
          command: 'login'
      - task: Docker@2
        displayName: Build and push
        inputs:
          command: 'buildAndPush'
          repository: elle
          tags: |
            latest
            $(Build.BuildId)