trigger:
- main
pr:
- main

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet build --configuration $(buildConfiguration)
    displayName: 'Build $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Stage artifacts'
    inputs:
      command: publish
      publishWebProjects: false
      arguments: '--configuration Release --runtime linux-x64 --self-contained --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts'
    inputs:
      ArtifactName: 'elle-$(Build.BuildNumber)'
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'Container'

  - task: AzureRmWebAppDeployment@4
    displayName: 'Deploy'
    inputs:
      ConnectionType: 'AzureRM'
      azureSubscription: 'azureConnection'
      WebAppName: $(TestWebAppName)
      packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
