trigger:
- main
- no-docker-deploy
pr:
- main

stages:
- stage:
  jobs:
  - job:
    steps:
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration Release'
      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration Release --runtime win-x86 --self-contained --output $(Build.ArtifactStagingDirectory)'
          zipAfterPublish: true
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'azureConnection'
          WebAppName: ellecal
          packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
